
final List<Map<String, dynamic>> categories = [
  {"icon": "assets/icons/neurology.png", "label": "Neurologist"},
  {"icon": "assets/icons/cardiology.png", "label": "Cardiology"},
  {"icon": "assets/icons/dermatologist.png", "label": "Dermatologist"},
  {"icon": "assets/icons/psychiatrist.png", "label": "Psychiatrist"},
  {"icon": "assets/icons/gynecologist.png", "label": "Gynecologist"},
  {"icon": "assets/icons/oncology.png", "label": "Oncologist"},
  {"icon": "assets/icons/pediatric.png", "label": "Pediatrician"},
  {"icon": "assets/icons/nephrologist.png", "label": "Nephrologist"},
  {"icon": "assets/icons/hematologist.png", "label": "Hematologist"},
  {"icon": "assets/icons/ophthalmology.png", "label": "Ophthalmologist"},
  {"icon": "assets/icons/gastroenterologist.png", "label": "Gastroenterologist"},
  {"icon": "assets/icons/urology.png", "label": "Urologist"},
];

final List<Map<String, dynamic>> doctors = [
  {"id": 1, "name": "Dr. John Smith", "city": "New York", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 12, "rating": 4.8},
  {"id": 2, "name": "Dr. Emily Brown", "city": "Los Angeles", "speciality": "Cardiologist", "category": "Heart", "experience": 15, "rating": 4.9},
  {"id": 3, "name": "Dr. Michael Davis", "city": "Chicago", "speciality": "Dermatologist", "category": "Skin", "experience": 8, "rating": 4.5},
  {"id": 4, "name": "Dr. Sarah Wilson", "city": "Houston", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 10, "rating": 4.7},
  {"id": 5, "name": "Dr. Robert Taylor", "city": "Phoenix", "speciality": "Gynecologist", "category": "Women's Health", "experience": 14, "rating": 4.6},
  {"id": 6, "name": "Dr. Jessica Martinez", "city": "Philadelphia", "speciality": "Oncologist", "category": "Cancer", "experience": 11, "rating": 4.8},
  {"id": 7, "name": "Dr. Daniel Anderson", "city": "San Antonio", "speciality": "Pediatrician", "category": "Children", "experience": 9, "rating": 4.4},
  {"id": 8, "name": "Dr. Nancy Thomas", "city": "San Diego", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 13, "rating": 4.9},
  {"id": 9, "name": "Dr. Richard Lee", "city": "Dallas", "speciality": "Cardiologist", "category": "Heart", "experience": 16, "rating": 4.8},
  {"id": 10, "name": "Dr. Patricia Garcia", "city": "San Jose", "speciality": "Dermatologist", "category": "Skin", "experience": 7, "rating": 4.3},
  {"id": 11, "name": "Dr. Christopher Miller", "city": "Austin", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 12, "rating": 4.6},
  {"id": 12, "name": "Dr. Karen Moore", "city": "Jacksonville", "speciality": "Gynecologist", "category": "Women's Health", "experience": 18, "rating": 4.7},
  {"id": 13, "name": "Dr. Thomas Harris", "city": "San Francisco", "speciality": "Oncologist", "category": "Cancer", "experience": 14, "rating": 4.9},
  {"id": 14, "name": "Dr. Barbara White", "city": "Columbus", "speciality": "Pediatrician", "category": "Children", "experience": 11, "rating": 4.5},
  {"id": 15, "name": "Dr. Steven Clark", "city": "Fort Worth", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 9, "rating": 4.4},
  {"id": 16, "name": "Dr. Elizabeth Lewis", "city": "Charlotte", "speciality": "Cardiologist", "category": "Heart", "experience": 20, "rating": 5.0},
  {"id": 17, "name": "Dr. James Walker", "city": "Indianapolis", "speciality": "Dermatologist", "category": "Skin", "experience": 10, "rating": 4.6},
  {"id": 18, "name": "Dr. Lisa Hall", "city": "Seattle", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 14, "rating": 4.8},
  {"id": 19, "name": "Dr. Matthew Allen", "city": "Denver", "speciality": "Gynecologist", "category": "Women's Health", "experience": 12, "rating": 4.5},
  {"id": 20, "name": "Dr. Sandra Young", "city": "Washington", "speciality": "Oncologist", "category": "Cancer", "experience": 16, "rating": 4.9},
  {"id": 21, "name": "Dr. Anthony King", "city": "Boston", "speciality": "Pediatrician", "category": "Children", "experience": 8, "rating": 4.3},
  {"id": 22, "name": "Dr. Deborah Hernandez", "city": "El Paso", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 15, "rating": 4.7},
  {"id": 23, "name": "Dr. Brian Scott", "city": "Nashville", "speciality": "Cardiologist", "category": "Heart", "experience": 13, "rating": 4.8},
  {"id": 24, "name": "Dr. Michelle Green", "city": "Detroit", "speciality": "Dermatologist", "category": "Skin", "experience": 9, "rating": 4.4},
  {"id": 25, "name": "Dr. Kevin Adams", "city": "Memphis", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 11, "rating": 4.5},
  {"id": 26, "name": "Dr. Laura Baker", "city": "Louisville", "speciality": "Gynecologist", "category": "Women's Health", "experience": 14, "rating": 4.6},
  {"id": 27, "name": "Dr. Mark Gonzalez", "city": "Baltimore", "speciality": "Oncologist", "category": "Cancer", "experience": 10, "rating": 4.7},
  {"id": 28, "name": "Dr. Donna Carter", "city": "Milwaukee", "speciality": "Pediatrician", "category": "Children", "experience": 7, "rating": 4.2},
  {"id": 29, "name": "Dr. Charles Rodriguez", "city": "Albuquerque", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 16, "rating": 4.9},
  {"id": 30, "name": "Dr. Rebecca Sanchez", "city": "Tucson", "speciality": "Cardiologist", "category": "Heart", "experience": 12, "rating": 4.8},
  {"id": 31, "name": "Dr. William Perez", "city": "Fresno", "speciality": "Dermatologist", "category": "Skin", "experience": 8, "rating": 4.3},
  {"id": 32, "name": "Dr. Cynthia Evans", "city": "Sacramento", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 10, "rating": 4.5},
  {"id": 33, "name": "Dr. Timothy Edwards", "city": "Mesa", "speciality": "Gynecologist", "category": "Women's Health", "experience": 18, "rating": 4.7},
  {"id": 34, "name": "Dr. Linda Collins", "city": "Atlanta", "speciality": "Oncologist", "category": "Cancer", "experience": 14, "rating": 4.9},
  {"id": 35, "name": "Dr. George Stewart", "city": "Kansas City", "speciality": "Pediatrician", "category": "Children", "experience": 11, "rating": 4.5},
  {"id": 36, "name": "Dr. Amanda Morris", "city": "Omaha", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 13, "rating": 4.8},
  {"id": 37, "name": "Dr. Scott Ramirez", "city": "Raleigh", "speciality": "Cardiologist", "category": "Heart", "experience": 15, "rating": 4.9},
  {"id": 38, "name": "Dr. Joshua Morgan", "city": "Miami", "speciality": "Dermatologist", "category": "Skin", "experience": 9, "rating": 4.4},
  {"id": 39, "name": "Dr. Megan Cooper", "city": "Oakland", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 12, "rating": 4.6},
  {"id": 40, "name": "Dr. Eric Rivera", "city": "Minneapolis", "speciality": "Gynecologist", "category": "Women's Health", "experience": 14, "rating": 4.7},
];

final List<Map<String, dynamic>> patients = [
  {
    "id": "1",
    "firstName": "Habib",
    "lastName": "Ullah",
    "email": "habibullah@gmail.com",
    "phone": "03496563330",
    "dob": "2001-01-16",
    "gender": "Male",
    "age": 24,
    "marital_status": "Single"
  }
];

final List<Map<String, dynamic>> appointments = [
  {
    "id": "1",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. John Smith",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-06",
    "time": "10:00 AM",
    "reason": "Check-up",
    "status": "Pending",
  },
  {
    "id": "2",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. Jane Doe",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-07",
    "time": "2:00 PM",
    "reason": "Follow-up",
    "status": "Approved",
  },
  {
    "id": "3",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. John Smith",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-08",
    "time": "9:00 AM",
    "reason": "Check-up",
    "status": "Completed",
  },
  {
    "id": "4",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. Jane Doe",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-09",
    "time": "1:00 PM",
    "reason": "Follow-up",
    "status": "Cancelled",
  },

];
