
final List<Map<String, dynamic>> categories = [
  {"icon": "assets/icons/neurology.png", "label": "Neurologist"},
  {"icon": "assets/icons/cardiology.png", "label": "Cardiologist"},
  {"icon": "assets/icons/dermatologist.png", "label": "Dermatologist"},
  {"icon": "assets/icons/psychiatrist.png", "label": "Psychiatrist"},
  {"icon": "assets/icons/gynecologist.png", "label": "Gynecologist"},
  {"icon": "assets/icons/oncology.png", "label": "Oncologist"},
  {"icon": "assets/icons/pediatric.png", "label": "Pediatrician"},
  {"icon": "assets/icons/nephrologist.png", "label": "Nephrologist"},
  {"icon": "assets/icons/hematologist.png", "label": "Hematologist"},
  {"icon": "assets/icons/ophthalmology.png", "label": "Ophthalmologist"},
  {"icon": "assets/icons/gastroenterologist.png", "label": "Gastroenterologist"},
  {"icon": "assets/icons/urology.png", "label": "Urologist"},
  {"icon": "assets/icons/Endocrinologist.png", "label": "Endocrinologist"},
  {"icon": "assets/icons/Rheumatologist.png", "label": "Rheumatologist"},
  {"icon": "assets/icons/Pulmonologist.png", "label": "Pulmonologist"},
  {"icon": "assets/icons/Orthopedic.png", "label": "Orthopedic"},
  {"icon": "assets/icons/General Surgeon.png", "label": "General Surgeon"},
  {"icon": "assets/icons/ENT Specialist.png", "label": "ENT Specialist"},
  {"icon": "assets/icons/Anesthesiologist.png", "label": "Anesthesiologist"},
];

final List<Map<String, dynamic>> doctors = [
{"id": 1, "name": "Dr. John Smith", "city": "New York", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 12, "rating": 4.8},
{"id": 2, "name": "Dr. Emily Brown", "city": "Los Angeles", "speciality": "Cardiologist", "category": "Heart", "experience": 15, "rating": 4.9},
{"id": 3, "name": "Dr. Michael Johnson", "city": "Chicago", "speciality": "Dermatologist", "category": "Skin", "experience": 10, "rating": 4.7},
{"id": 4, "name": "Dr. Sarah Davis", "city": "Houston", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 14, "rating": 4.6},
{"id": 5, "name": "Dr. David Wilson", "city": "Phoenix", "speciality": "Gynecologist", "category": "Women's Health", "experience": 11, "rating": 4.8},
{"id": 6, "name": "Dr. Laura Martinez", "city": "Philadelphia", "speciality": "Oncologist", "category": "Cancer", "experience": 16, "rating": 4.9},
{"id": 7, "name": "Dr. James Anderson", "city": "San Antonio", "speciality": "Pediatrician", "category": "Child Health", "experience": 13, "rating": 4.7},
{"id": 8, "name": "Dr. Emma Taylor", "city": "San Diego", "speciality": "Nephrologist", "category": "Kidney", "experience": 9, "rating": 4.5},
{"id": 9, "name": "Dr. Daniel Thomas", "city": "Dallas", "speciality": "Hematologist", "category": "Blood", "experience": 12, "rating": 4.8},
{"id": 10, "name": "Dr. Olivia Moore", "city": "San Jose", "speciality": "Ophthalmologist", "category": "Eye", "experience": 10, "rating": 4.6},
{"id": 11, "name": "Dr. William Jackson", "city": "Austin", "speciality": "Gastroenterologist", "category": "Digestive System", "experience": 15, "rating": 4.9},
{"id": 12, "name": "Dr. Sophia White", "city": "Jacksonville", "speciality": "Urologist", "category": "Urinary System", "experience": 11, "rating": 4.7},
{"id": 13, "name": "Dr. Benjamin Harris", "city": "Fort Worth", "speciality": "Endocrinologist", "category": "Hormones", "experience": 14, "rating": 4.8},
{"id": 14, "name": "Dr. Mia Martin", "city": "Columbus", "speciality": "Rheumatologist", "category": "Joints", "experience": 10, "rating": 4.6},
{"id": 15, "name": "Dr. Lucas Thompson", "city": "Charlotte", "speciality": "Pulmonologist", "category": "Lungs", "experience": 12, "rating": 4.7},
{"id": 16, "name": "Dr. Ava Garcia", "city": "Indianapolis", "speciality": "Orthopedic", "category": "Bones", "experience": 13, "rating": 4.8},
{"id": 17, "name": "Dr. Ethan Martinez", "city": "San Francisco", "speciality": "General Surgeon", "category": "Surgery", "experience": 16, "rating": 4.9},
{"id": 18, "name": "Dr. Chloe Robinson", "city": "Seattle", "speciality": "ENT Specialist", "category": "Ear, Nose, Throat", "experience": 11, "rating": 4.7},
{"id": 19, "name": "Dr. Mason Clark", "city": "Denver", "speciality": "Anesthesiologist", "category": "Anesthesia", "experience": 14, "rating": 4.8},
{"id": 20, "name": "Dr. Harper Rodriguez", "city": "Washington", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 10, "rating": 4.6},
{"id": 21, "name": "Dr. Logan Lewis", "city": "Boston", "speciality": "Cardiologist", "category": "Heart", "experience": 15, "rating": 4.9},
{"id": 22, "name": "Dr. Amelia Walker", "city": "Nashville", "speciality": "Dermatologist", "category": "Skin", "experience": 12, "rating": 4.7},
{"id": 23, "name": "Dr. Caleb Hall", "city": "Baltimore", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 13, "rating": 4.8},
{"id": 24, "name": "Dr. Evelyn Young", "city": "Louisville", "speciality": "Gynecologist", "category": "Women's Health", "experience": 11, "rating": 4.6},
{"id": 25, "name": "Dr. Henry King", "city": "Portland", "speciality": "Oncologist", "category": "Cancer", "experience": 14, "rating": 4.8},
{"id": 26, "name": "Dr. Lily Wright", "city": "Oklahoma City", "speciality": "Pediatrician", "category": "Child Health", "experience": 10, "rating": 4.7},
{"id": 27, "name": "Dr. Alexander Scott", "city": "Las Vegas", "speciality": "Nephrologist", "category": "Kidney", "experience": 12, "rating": 4.8},
{"id": 28, "name": "Dr. Grace Green", "city": "Milwaukee", "speciality": "Hematologist", "category": "Blood", "experience": 15, "rating": 4.9},
{"id": 29, "name": "Dr. Jack Adams", "city": "Albuquerque", "speciality": "Ophthalmologist", "category": "Eye", "experience": 11, "rating": 4.7},
{"id": 30, "name": "Dr. Zoe Baker", "city": "Tucson", "speciality": "Gastroenterologist", "category": "Digestive System", "experience": 13, "rating": 4.8},
{"id": 31, "name": "Dr. Nathan Carter", "city": "Fresno", "speciality": "Urologist", "category": "Urinary System", "experience": 10, "rating": 4.6},
{"id": 32, "name": "Dr. Victoria Perez", "city": "Sacramento", "speciality": "Endocrinologist", "category": "Hormones", "experience": 14, "rating": 4.8},
{"id": 33, "name": "Dr. Samuel Turner", "city": "Kansas City", "speciality": "Rheumatologist", "category": "Joints", "experience": 12, "rating": 4.7},
{"id": 34, "name": "Dr. Hannah Phillips", "city": "Atlanta", "speciality": "Pulmonologist", "category": "Lungs", "experience": 11, "rating": 4.6},
{"id": 35, "name": "Dr. Dylan Campbell", "city": "Miami", "speciality": "Orthopedic", "category": "Bones", "experience": 15, "rating": 4.9},
{"id": 36, "name": "Dr. Addison Parker", "city": "Raleigh", "speciality": "General Surgeon", "category": "Surgery", "experience": 13, "rating": 4.8},
{"id": 37, "name": "Dr. Ryan Evans", "city": "Omaha", "speciality": "ENT Specialist", "category": "Ear, Nose, Throat", "experience": 10, "rating": 4.7},
{"id": 38, "name": "Dr. Natalie Edwards", "city": "Minneapolis", "speciality": "Anesthesiologist", "category": "Anesthesia", "experience": 12, "rating": 4.8},
{"id": 39, "name": "Dr. Luke Collins", "city": "Tulsa", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 14, "rating": 4.9},
{"id": 40, "name": "Dr. Savannah Stewart", "city": "Cleveland", "speciality": "Cardiologist", "category": "Heart", "experience": 11, "rating": 4.7},
{"id": 41, "name": "Dr. Jordan Sanchez", "city": "Wichita", "speciality": "Dermatologist", "category": "Skin", "experience": 13, "rating": 4.8},
{"id": 42, "name": "Dr. Brooklyn Morris", "city": "Arlington", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 10, "rating": 4.6},
{"id": 43, "name": "Dr. Aaron Rogers", "city": "New Orleans", "speciality": "Gynecologist", "category": "Women's Health", "experience": 15, "rating": 4.9},
{"id": 44, "name": "Dr. Leah Reed", "city": "Bakersfield", "speciality": "Oncologist", "category": "Cancer", "experience": 12, "rating": 4.8},
{"id": 45, "name": "Dr. Evan Cook", "city": "Tampa", "speciality": "Pediatrician", "category": "Child Health", "experience": 11, "rating": 4.7},
{"id": 46, "name": "Dr. Ariana Morgan", "city": "Honolulu", "speciality": "Nephrologist", "category": "Kidney", "experience": 14, "rating": 4.8},
{"id": 47, "name": "Dr. Gabriel Bell", "city": "Anaheim", "speciality": "Hematologist", "category": "Blood", "experience": 13, "rating": 4.7},
{"id": 48, "name": "Dr. Makayla Murphy", "city": "Santa Ana", "speciality": "Ophthalmologist", "category": "Eye", "experience": 10, "rating": 4.6},
{"id": 49, "name": "Dr. Connor Bailey", "city": "Riverside", "speciality": "Gastroenterologist", "category": "Digestive System", "experience": 12, "rating": 4.8},
{"id": 50, "name": "Dr. Paige Rivera", "city": "Corpus Christi", "speciality": "Urologist", "category": "Urinary System", "experience": 11, "rating": 4.7},
{"id": 51, "name": "Dr. Jason Cooper", "city": "Lexington", "speciality": "Endocrinologist", "category": "Hormones", "experience": 14, "rating": 4.9},
{"id": 52, "name": "Dr. Kennedy Richardson", "city": "Stockton", "speciality": "Rheumatologist", "category": "Joints", "experience": 13, "rating": 4.8},
{"id": 53, "name": "Dr. Isaiah Howard", "city": "Henderson", "speciality": "Pulmonologist", "category": "Lungs", "experience": 10, "rating": 4.7},
{"id": 54, "name": "Dr. Brianna Ward", "city": "Saint Paul", "speciality": "Orthopedic", "category": "Bones", "experience": 12, "rating": 4.8},
{"id": 55, "name": "Dr. Josiah Torres", "city": "Cincinnati", "speciality": "General Surgeon", "category": "Surgery", "experience": 15, "rating": 4.9},
{"id": 56, "name": "Dr. Lyla Peterson", "city": "Greensboro", "speciality": "ENT Specialist", "category": "Ear, Nose, Throat", "experience": 11, "rating": 4.7},
{"id": 57, "name": "Dr. Adrian Gray", "city": "Pittsburgh", "speciality": "Anesthesiologist", "category": "Anesthesia", "experience": 14, "rating": 4.8},
{"id": 58, "name": "Dr. Clara Ramirez", "city": "Lincoln", "speciality": "Neurologist", "category": "Brain & Nerves", "experience": 13, "rating": 4.7},
{"id": 59, "name": "Dr. Eli James", "city": "Orlando", "speciality": "Cardiologist", "category": "Heart", "experience": 10, "rating": 4.6},
{"id": 60, "name": "Dr. Nevaeh Watson", "city": "Plano", "speciality": "Dermatologist", "category": "Skin", "experience": 12, "rating": 4.8},
{"id": 61, "name": "Dr. Landon Brooks", "city": "Irvine", "speciality": "Psychiatrist", "category": "Mental Health", "experience": 11, "rating": 4.7},
{"id": 62, "name": "Dr. Ruby Kelly", "city": "Newark", "speciality": "Gynecologist", "category": "Women's Health", "experience": 14, "rating": 4.9},
{"id": 63, "name": "Dr. Xavier Sanders", "city": "Durham", "speciality": "Oncologist", "category": "Cancer", "experience": 13, "rating": 4.8},
{"id": 64, "name": "Dr. Piper Price", "city": "Chandler", "speciality": "Pediatrician", "category": "Child Health", "experience": 10, "rating": 4.7},
{"id": 65, "name": "Dr. Asher Bennett", "city": "Buffalo", "speciality": "Nephrologist", "category": "Kidney", "experience": 12, "rating": 4.8},
{"id": 66, "name": "Dr. Ellie Wood", "city": "Madison", "speciality": "Hematologist", "category": "Blood", "experience": 11, "rating": 4.7},
{"id": 67, "name": "Dr. Jude Barnes", "city": "Fort Wayne", "speciality": "Ophthalmologist", "category": "Eye", "experience": 14, "rating": 4.9},
{"id": 68, "name": "Dr. Sadie Ross", "city": "Richmond", "speciality": "Gastroenterologist", "category": "Digestive System", "experience": 13, "rating": 4.8},
{"id": 69, "name": "Dr. Axel Henderson", "city": "Boise", "speciality": "Urologist", "category": "Urinary System", "experience": 10, "rating": 4.7},
{"id": 70, "name": "Dr. Delilah Coleman", "city": "San Bernardino", "speciality": "Endocrinologist", "category": "Hormones", "experience": 12, "rating": 4.8},
{"id": 71, "name": "Dr. Sawyer Jenkins", "city": "Baton Rouge", "speciality": "Rheumatologist", "category": "Joints", "experience": 11, "rating": 4.7},
{"id": 72, "name": "Dr. Emery Perry", "city": "Spokane", "speciality": "Pulmonologist", "category": "Lungs", "experience": 14, "rating": 4.9},
{"id": 73, "name": "Dr. Remi Powell", "city": "Toledo", "speciality": "Orthopedic", "category": "Bones", "experience": 13, "rating": 4.8},
{"id": 74, "name": "Dr. Knox Long", "city": "Irving", "speciality": "General Surgeon", "category": "Surgery", "experience": 10, "rating": 4.7},
{"id": 75, "name": "Dr. Reese Flores", "city": "Lubbock", "speciality": "ENT Specialist", "category": "Ear, Nose, Throat", "experience": 12, "rating": 4.8},
];

final List<Map<String, dynamic>> patients = [
  {
    "id": "1",
    "firstName": "Habib",
    "lastName": "Ullah",
    "email": "habibullah@gmail.com",
    "phone": "03496563330",
    "dob": "2001-01-16",
    "gender": "Male",
    "age": 24,
    "marital_status": "Single"
  }
];

final List<Map<String, dynamic>> appointments = [
  {
    "id": "1",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. John Smith",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-06",
    "time": "10:00 AM",
    "reason": "Check-up",
    "status": "Pending",
  },
  {
    "id": "2",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. Jane Doe",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-07",
    "time": "2:00 PM",
    "reason": "Follow-up",
    "status": "Approved",
  },
  {
    "id": "3",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. John Smith",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-08",
    "time": "9:00 AM",
    "reason": "Check-up",
    "status": "Completed",
  },
  {
    "id": "4",
    "patient_name": "Habib Ullah",
    "doctor_name": "Dr. Jane Doe",
    "doctor_picture": "assets/icons/doctor.png",
    "date": "2023-08-09",
    "time": "1:00 PM",
    "reason": "Follow-up",
    "status": "Cancelled",
  },

];
